#!/usr/bin/env sh

os="$(uname)"


if [ "$os" = "Darwin" ]; then
    ansible-playbook --ask-become-pass \
        -i hosts \
        mac.yml
elif [ "$os" = "Linux" ]; then
    # Installs ansible
    apt-get update && apt-get install -y ansible

    ansible-playbook --ask-become-pass -i hosts linux.yml --check
else
   echo "Unknow OS: $os"
   exit 1
fi
